INSERT INTO zones (id, name, slug, description, sort_order, required_level, status)
VALUES
  ('zone-html', '新手村', 'html-beginner', '学习 HTML 结构、文本、链接、列表与表单，完成你的第一张网页名片。', 1, 1, 'active'),
  ('zone-css', 'CSS 森林', 'css-forest', '学习选择器、文本样式、卡片样式与盒模型，让页面真正好看起来。', 2, 2, 'active'),
  ('zone-js', 'JS 风暴', 'js-storm', '学习变量、函数、DOM 与交互逻辑，让页面拥有真正的生命。', 3, 4, 'active')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  slug = VALUES(slug),
  description = VALUES(description),
  sort_order = VALUES(sort_order),
  required_level = VALUES(required_level),
  status = VALUES(status);

INSERT INTO levels (
  id,
  zone_id,
  title,
  description,
  story,
  difficulty,
  sort_order,
  reward_xp,
  starter_code_html,
  starter_code_css,
  starter_code_js,
  required_keywords,
  status
)
VALUES
  (
    'level-001',
    'zone-html',
    '认识网页骨架',
    '用 main、h1 和 p 搭起第一张网页公告板。',
    '你刚进入新手村，村口的公告板还是空的。村长让你把欢迎信息写上去，让所有来到 WebQuest 的冒险者都知道这里是旅程的起点。',
    'easy',
    1,
    10,
    '<main>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("WebQuest ready");',
    JSON_ARRAY('<main', '<h1', '<p'),
    'active'
  ),
  (
    'level-002',
    'zone-html',
    '文本标签入门',
    '学习二级标题、段落和强调标签的基础用法。',
    '村长交给你第一份正式任务：制作一份任务说明书，让新人知道本次冒险的重点和注意事项。',
    'easy',
    2,
    12,
    '<main>\n  <h1>新手村公告</h1>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("mission loaded");',
    JSON_ARRAY('<h2', '<p', '<strong', '<em'),
    'active'
  ),
  (
    'level-003',
    'zone-html',
    '图片与链接',
    '学习插入图片、补充 alt 描述和创建超链接。',
    '村里的档案馆需要为你的冒险者档案添加头像和资料入口，这样其他人就能快速认识你。',
    'easy',
    3,
    14,
    '<main>\n  <h1>我的冒险者档案</h1>\n  <p>欢迎来到 WebQuest。</p>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("profile ready");',
    JSON_ARRAY('<img', 'src=', 'alt=', '<a', 'href='),
    'active'
  ),
  (
    'level-004',
    'zone-html',
    '列表与信息分组',
    '用 section、div、ul 和 li 组织结构化信息。',
    '村里的导师要求你把自己的初始技能整理成清单，便于后续升级记录。',
    'easy',
    4,
    16,
    '<main>\n  <h1>冒险者技能档案</h1>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("skills ready");',
    JSON_ARRAY('<section', '<ul', '<li', '<div'),
    'active'
  ),
  (
    'level-005',
    'zone-html',
    '表单与输入控件',
    '学习 form、label、input 和 button 的配合用法。',
    '你已经完成基础训练，守门员要求你制作一张入村登记表，记录每位冒险者的名字和职业。',
    'medium',
    5,
    18,
    '<main>\n  <h1>新手村登记处</h1>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("register form");',
    JSON_ARRAY('<form', '<label', '<input', '<button'),
    'active'
  ),
  (
    'level-006',
    'zone-html',
    'Boss - 个人介绍页',
    '综合前 5 关 HTML 知识，完成一张完整的冒险者介绍页。',
    '为了正式加入 WebQuest 冒险者公会，你需要提交一份个人介绍页，展示自己的身份、目标和掌握的初始技能。',
    'hard',
    6,
    25,
    '<main>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("profile page start");',
    JSON_ARRAY('<h1', '<img', 'alt=', '<ul', '<li', '<a', 'href='),
    'active'
  ),
  (
    'level-007',
    'zone-css',
    'CSS 选择器入门',
    '学习标签选择器、类选择器以及颜色、背景色的基础写法。',
    '新手村的公告板内容已经写好，但看起来太普通了。你需要用样式让重要信息更容易被看到。',
    'easy',
    7,
    12,
    '<main class="board">\n  <h1>新手村公告板</h1>\n  <p>欢迎来到 WebQuest。</p>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("css start");',
    JSON_ARRAY('.board', 'color', 'background-color'),
    'active'
  ),
  (
    'level-008',
    'zone-css',
    '字体与文本样式',
    '用字号、字重、对齐和行高建立信息层级。',
    '导师发现你的任务说明文字太平淡了，阅读起来费劲。他要求你优化标题和正文，让信息层级更清晰。',
    'easy',
    8,
    14,
    '<main class="mission-card">\n  <h1>今日任务</h1>\n  <p>完成一份清晰易读的任务说明。</p>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("text styles");',
    JSON_ARRAY('font-size', 'font-weight', 'text-align', 'line-height'),
    'active'
  ),
  (
    'level-009',
    'zone-css',
    '背景与边框',
    '学习背景、边框和圆角，让内容区域更像一个组件。',
    '公告内容有了，但村里的任务卡片还是像普通文字一样散在页面里。你需要给它做出真正的卡片感。',
    'easy',
    9,
    16,
    '<main>\n  <section class="task-card">\n    <h1>主线任务</h1>\n    <p>完成你的第一张冒险任务卡。</p>\n  </section>\n</main>',
    'body {\n  font-family: sans-serif;\n}',
    'console.log("card ready");',
    JSON_ARRAY('background', 'border', 'border-radius'),
    'active'
  ),
  (
    'level-010',
    'zone-css',
    '盒模型与间距',
    '学习 padding、margin 和宽度控制，让卡片更有呼吸感。',
    '任务卡已经做出来了，但里面的文字紧贴边框，多个模块之间也毫无间隔。导师要求你调整布局，让内容更易读。',
    'medium',
    10,
    18,
    '<main>\n  <section class="task-card">\n    <h1>冒险提示</h1>\n    <p>请调整卡片的间距，让页面更清晰。</p>\n  </section>\n</main>',
    'body {\n  font-family: sans-serif;\n}\n\n.task-card {\n  border: 1px solid #333;\n  border-radius: 12px;\n}',
    'console.log("spacing challenge");',
    JSON_ARRAY('padding', 'margin', 'width'),
    'active'
  ),
  (
    'level-011',
    'zone-css',
    'display 与元素排布',
    '学习用 display 控制元素是独占一行还是横向排布。',
    '你制作了一组技能徽章，但它们现在挤在一起或换行混乱。你需要调整它们的显示方式。',
    'medium',
    11,
    20,
    '<main>\n  <div class="badge">HTML</div>\n  <div class="badge">CSS</div>\n  <div class="badge">JavaScript</div>\n</main>',
    'body {\n  font-family: sans-serif;\n}\n\n.badge {\n  border: 1px solid #333;\n  border-radius: 999px;\n  padding: 6px 12px;\n}',
    'console.log("badge layout");',
    JSON_ARRAY('.badge', 'display', 'inline-block'),
    'active'
  ),
  (
    'level-012',
    'zone-css',
    'Boss - 个人资料卡片美化',
    '综合第二章全部样式知识，把资料页升级成一张完整的产品化卡片。',
    '公会管理员已经收到你的个人介绍页，但他说：内容合格，表现力不足。现在你需要把这份资料页升级成真正能展示给全村看的冒险者名片。',
    'hard',
    12,
    30,
    '<main class="profile-card">\n  <img src="https://dummyimage.com/120x120/cccccc/000000" alt="冒险者头像" />\n  <h1>代码冒险家</h1>\n  <p>正在学习 HTML 和 CSS，准备开启更深入的前端旅程。</p>\n\n  <section class="skills">\n    <h2>已掌握技能</h2>\n    <div class="badge">HTML</div>\n    <div class="badge">CSS</div>\n    <div class="badge">Git</div>\n  </section>\n\n  <a href="https://example.com">查看我的作品</a>\n</main>',
    'body {\n  font-family: sans-serif;\n}\n\n.badge {\n  border: 1px solid #333;\n  border-radius: 999px;\n}',
    'console.log("css boss");',
    JSON_ARRAY('background', 'border', 'border-radius', 'padding', 'margin', 'display'),
    'active'
  )
ON DUPLICATE KEY UPDATE
  zone_id = VALUES(zone_id),
  title = VALUES(title),
  description = VALUES(description),
  story = VALUES(story),
  difficulty = VALUES(difficulty),
  sort_order = VALUES(sort_order),
  reward_xp = VALUES(reward_xp),
  starter_code_html = VALUES(starter_code_html),
  starter_code_css = VALUES(starter_code_css),
  starter_code_js = VALUES(starter_code_js),
  required_keywords = VALUES(required_keywords),
  status = VALUES(status);
